workflow test smart

diff --git a/.github/workflows/py_testing.yml b/.github/workflows/py_testing.yml
--- a/.github/workflows/py_testing.yml
+++ b/.github/workflows/py_testing.yml
@@ -31,27 +31,40 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install tox
-      - name: Perform Python 3.7 unit testing
-        id: py37
+      - name: Obtain list of valid lambda dirs
+        id: dirlist
         env:
           LATEST_COMMIT: ${{ github.event.pull_request.head.sha }}
-          CURR_PYTHON_VER: py37
         run: |
           cd $GITHUB_WORKSPACE
           numb_commits=$(git rev-list --count origin/master..$LATEST_COMMIT)
           IFS=$'\n' dir_list=( $(git --no-pager diff --dirstat=files,0 origin/master~${numb_commits} | sed -E 's/^[ 0-9.]+% //g') )
           
-          errored_lambdas=""
+          lambda_dirs=""
           for curr_dir in "${dir_list[@]}"
           do
             files_in_dir=$(find ${curr_dir} -maxdepth 1 -name "tox.ini" 2>/dev/null | wc -l)
             if [ ${files_in_dir} -ge 1 ]; then
-              cd $GITHUB_WORKSPACE/${curr_dir}
-              tox -e "${CURR_PYTHON_VER}" | tee output.txt || true
-              cat output.txt | grep -q InvocationError
-              if [ $? -eq 0 ]; then
-                errored_lambdas="${errored_lambdas} $(basename $GITHUB_WORKSPACE/${curr_dir})"
-              fi
+              lambda_dirs="$GITHUB_WORKSPACE/${curr_dir} ${lambda_dirs}"
+            fi
+          done
+          echo "::set-output name=lambdadirs::${lambda_dirs}"
+      - name: Perform Python 3.7 unit testing
+        id: py37
+        env:
+          CURR_PYTHON_VER: py37
+          DIR_LIST: ${{ steps.dirlist.outputs.lambdadirs }}
+        run: |
+          IFS=$' ' dir_list=( $(echo ${DIR_LIST}) )
+          
+          errored_lambdas=""
+          for curr_dir in "${dir_list[@]}"
+          do
+            cd ${curr_dir}
+            tox -e "${CURR_PYTHON_VER}" | tee output.txt || true
+            cat output.txt | grep -q InvocationError
+            if [ $? -eq 0 ]; then
+              errored_lambdas="${errored_lambdas} $(basename $GITHUB_WORKSPACE/${curr_dir})"
             fi
           done
           echo "::set-output name=erroredlambdas::${errored_lambdas}"
@@ -59,48 +72,38 @@ jobs:
       - name: Perform Python 3.8 unit testing
         id: py38
         env:
-          LATEST_COMMIT: ${{ github.event.pull_request.head.sha }}
           CURR_PYTHON_VER: py38
-          PREV_OUTPUT: ${{ steps.py37.outputs.erroredlambdas }}
+          DIR_LIST: ${{ steps.dirlist.outputs.lambdadirs }}
+          FAILED_LAMBDA_LIST: ${{ steps.py37.outputs.erroredlambdas }}
         run: |
-          cd $GITHUB_WORKSPACE
-          numb_commits=$(git rev-list --count origin/master..$LATEST_COMMIT)
-          IFS=$'\n' dir_list=( $(git --no-pager diff --dirstat=files,0 origin/master~${numb_commits} | sed -E 's/^[ 0-9.]+% //g') )
+          IFS=$' ' dir_list=( $(echo ${DIR_LIST}) )
           
           errored_lambdas=""
           for curr_dir in "${dir_list[@]}"
           do
-            files_in_dir=$(find ${curr_dir} -maxdepth 1 -name "tox.ini" 2>/dev/null | wc -l)
-            if [ ${files_in_dir} -ge 1 ]; then
-              cd $GITHUB_WORKSPACE/${curr_dir} 
-              tox -e "${CURR_PYTHON_VER}" | tee output.txt || true
-              cat output.txt | grep -q InvocationError
-              if [ $? -eq 0 ]; then
-                errored_lambdas="${errored_lambdas} $(basename $GITHUB_WORKSPACE/${curr_dir})"
-              fi
+            cd ${curr_dir}
+            tox -e "${CURR_PYTHON_VER}" | tee output.txt || true
+            cat output.txt | grep -q InvocationError
+            if [ $? -eq 0 ]; then
+              errored_lambdas="${errored_lambdas} $(basename $GITHUB_WORKSPACE/${curr_dir})"
             fi
           done
-          echo "::set-output name=erroredlambdas::${PREV_OUTPUT} ${errored_lambdas}"
+          echo "::set-output name=erroredlambdas::${errored_lambdas}"
         continue-on-error: true
-      - name: Verify tests
+      - name: Verify test results
         env:
-          LATEST_COMMIT: ${{ github.event.pull_request.head.sha }}
-          PREV_OUTPUT: ${{ steps.py38.outputs.erroredlambdas }}
+          DIR_LIST: ${{ steps.dirlist.outputs.lambdadirs }}
+          FAILED_LAMBDA_LIST: ${{ steps.py38.outputs.erroredlambdas }}
         run: |
-          cd $GITHUB_WORKSPACE
-          numb_commits=$(git rev-list --count origin/master..$LATEST_COMMIT)
-          IFS=$'\n' dir_list=( $(git --no-pager diff --dirstat=files,0 origin/master~${numb_commits} | sed -E 's/^[ 0-9.]+% //g') )
+          IFS=$' ' dir_list=( $(echo ${DIR_LIST}) )
           
-          has_failed="false"
+          has_failed=""
           for curr_dir in "${dir_list[@]}"
           do
-            files_in_dir=$(find ${curr_dir} -maxdepth 1 -name "tox.ini" 2>/dev/null | wc -l)
-            if [ ${files_in_dir} -ge 1 ]; then
-              lambda_name=$(basename $GITHUB_WORKSPACE/${curr_dir})
-              if [ $(echo ${PREV_OUTPUT} | grep -o ${lambda_name} | wc -l) -ge 2 ]; then
-                  echo "::error ::Lambda function, ${lambda_name}, failed in multiple test environments!"
-                  has_failed="true"
-              fi
+            lambda_name=$(basename $GITHUB_WORKSPACE/${curr_dir})
+            if [ $(echo ${FAILED_LAMBDA_LIST} | grep -o ${lambda_name} | wc -l) -ge 2 ]; then
+              echo "::error ::Lambda function, ${lambda_name}, failed in multiple test environments!"
+              has_failed="true"
             fi
           done
 
